{
 "title": "PetFinder Demo",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Output Logits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(output_prediction_value_logits_sum[$__rate_interval])/rate(output_prediction_value_logits_count[$__rate_interval]))",
     "legendFormat": "Average predicted value"
    },
    {
     "expr": "sum(rate(output_prediction_value_logits_count[$__rate_interval]))",
     "legendFormat": "Number of predictions"
    },
    {
     "expr": "sum(rate(output_prediction_value_logits_sum[$__rate_interval]))",
     "legendFormat": "Sum of predictions"
    }
   ]
  },
  {
   "title": "Count by Pet Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(PetType)(rate(input_distribution_counts[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Count by Breed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(Breed)(rate(input_distribution_counts[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Count by Gender",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(Gender)(rate(input_distribution_counts[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Count by Color",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(Color)(rate(input_distribution_counts[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Count by Health",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(Health)(rate(input_distribution_counts[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Count by Maturity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(Maturity_Size)(rate(input_distribution_counts[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}