apiVersion: v1
data:
  example_sidecar_config.textproto: "# proto-file: api/proto/metricrule_metric_configuration.proto\n#
    proto-message: SidecarConfig\n\ninput_metrics {\n    name: \"input_distribution_counts\"\n
    \   simple_counter {}\n    labels {\n        label_key { string_value: \"Type\"
    }\n        label_value {\n            parsed_value {\n                field_path
    { paths: \"Type\" }\n                parsed_type: STRING\n            }\n        }\n
    \   }\n    labels {\n        label_key { string_value: \"Breed\" }\n        label_value
    {\n            parsed_value {\n                field_path { paths: \"Breed\" }\n
    \               parsed_type: STRING\n            }\n        }\n    }\n}\noutput_metrics
    {\n    name: \"output_prediction_value_logits\"\n    value {\n        value {\n\t\t
    \   parsed_value {\n\t\t\t\tfield_path { paths: \"prediction\" }\n\t\t\t\tparsed_type:
    FLOAT\n\t\t\t}\n        }\n    }\n}"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-25T07:45:54Z"
  name: petfinder-config-map
  namespace: default
  resourceVersion: "1216332"
  selfLink: /api/v1/namespaces/default/configmaps/petfinder-config-map
  uid: 6de6a6ce-b388-47bb-81d0-008ea47c8ef0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petfinder-deployment
spec:
  selector:
    matchLabels:
      app: petfinder-server
  replicas: 2
  template:
    metadata:
      labels:
        app: petfinder-server
    spec:
      containers:
      - name: petfinder-container
        image: asia.gcr.io/metricrule-tfserving-demo/petfinder
        ports:
        - containerPort: 8501
      - name: metricrule-sidecar-container
        image: metricrule/metricrule-sidecar-tfserving
        env:
        - name: APPLICATION_PORT
          value: "8501"
        - name: REVERSE_PROXY_PORT
          value: "8551"
        - name: SIDECAR_CONFIG_PATH
          value: "/config/sidecar.textproto"
        ports:
        - containerPort: 8551
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: petfinder-config-map
          items:
          - key: example_sidecar_config.textproto
            path: sidecar.textproto
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: petfinder-service
  name: petfinder-service
spec:
  ports:
  - port: 8501
    targetPort: 8551
  selector:
    app: petfinder-server
  type: LoadBalancer

