apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: sklearn-iris
spec:
  default:
    predictor:
      logger:
        mode: all
        url: http://dummy.agent.url/
      sklearn:
        storageUri: gs://kfserving-samples/models/sklearn/iris
