# proto-file: api/proto/metricrule_metric_configuration.proto
# proto-message: SidecarConfig

input_content_filter: ".instances[*]"
input_metrics {
    name: "input_distribution_counts"
    simple_counter {}
    labels {
        label_key { string_value: "Breed" }
        label_value {
            parsed_value {
                field_path: ".Breed1[0]"
                parsed_type: STRING
            }
        }
    }
}
output_content_filter: ".predictions[*]"
output_metrics {
    name: "output_prediction_value_logits"
    value {
        value {
            parsed_value {
                field_path: "[0]"
                parsed_type: FLOAT
            }
        }
        bins: -10
        bins: -3
        bins: 0
        bins: 3
        bins: 10
    }
}
context_labels_from_input {
    label_key { string_value: "PetType" }
    label_value {
        parsed_value {
            field_path: ".Type[0]"
            parsed_type: STRING
        }
    }
}