# proto-file: api/proto/metricrule_metric_configuration.proto
# proto-message: SidecarConfig

input_metrics {
    name: "input_distribution_counts"
    simple_counter {}
    labels {
        label_key { string_value: "Type" }
        label_value {
            parsed_value {
                field_path { paths: "Type" }
                parsed_type: STRING
            }
        }
    }
    labels {
        label_key { string_value: "Breed" }
        label_value {
            parsed_value {
                field_path { paths: "Breed" }
                parsed_type: STRING
            }
        }
    }
}
output_metrics {
    name: "output_prediction_value_logits"
    value {
        value {
		    parsed_value {
				field_path { paths: "prediction" }
				parsed_type: FLOAT
			}
        }
    }
}